### ISSUE TITLE
vue server component ideas

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/experiments#7]
cf. https://github.com/hi-ogawa/vite-plugins/issues/174

## todo

- [x] server component hmr https://github.com/hi-ogawa/experiments/pull/6
- [x] server/client convention https://github.com/hi-ogawa/experiments/pull/9
  - [x] `"server-pre"` build collects client components, but it doesn't need to recursively collect. We can avoid this by just returning "empty" code when transforming client boundary.
- [ ] server context
  - redirect, response header mutation
- [ ] server action
  - [ ] revalidation
- [ ] ssg? https://github.com/antfu-collective/vite-ssg
- [ ] stream serialize
- [ ] avoid waterfall of serialize + client reference fetching
  - [ ] prefetch?

**Comment by hi-ogawa** [comment]
Closing it as it's not on my main focus right now
